### ISSUE TITLE
sample data link is not working

### ISSUE THREAD

**Issue by wilsonlau-uw** [PreferredAI/mrg#1]
hi,  I really enjoyed your paper.   I am wondering if you can fix the link of the sample data, so we can learn from your code.  Thanks.

**Comment by qtuantruong** [comment]
@wilsonlau-uw we've updated the link to download the data. Please try again.

**Comment by wilsonlau-uw** [comment]
@tqtg  Thank you for your reply.  The google link requires access permission.  Please grant my access.  Thanks!
